service: serverless-nodejs-testing

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stage: dev
  environment: 
    WORLD_FUNC: ${self:service}-${self:provider.stage}-world
    LAMBDA_ENDPOINT: http://localhost:4001
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
          Resource: '*'
          
custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4001
    endpoint: http://localhost:4001

functions:
  hello:
    handler: functions/index.hello
    events:
      - http:
          path: /hello
          method: get
  world:
    handler: functions/index.world    
  reverse:
    handler: functions/reverseFunc.handler
    events:
      - http:
          path: /reverse
          method: get

plugins:
  - serverless-offline